{% set name = "pySOT" %}
{% set version = "0.2.2" %}
{% set sha256 = "a4817705fa40e8c4d3b5e5a42445036c2a966224b0d45f1c5f66d7c9c4d78455" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - scipy
    - pydoe
    - poap >=0.1.25
    - py_dempster_shafer

  run:
    - python
    - scipy
    - pydoe
    - poap >=0.1.25
    - py_dempster_shafer

test:
  imports:
    - pySOT
    - pySOT.test

  source_files:
    - pySOT/test

  commands:
    - cd pySOT
    - cd test
    - python test_simple.py
    - python test_simple_time.py
    - python test_rbf.py
    - python test_penalty.py
    - python test_projection.py
    - python test_ensemble.py
    - python test_gp_regression.py
    - python test_mixed_integer_constraints.py
    - python test_multisampling.py
    - python test_extra_vals.py
    
  requires:
    - scikit-learn ==0.18.1
    
about:
  home: https://github.com/dme65/pySOT
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: 'Surrogate Optimization Toolbox'
  description: |
    pySOT is an asynchronous parallel optimization toolbox for global deterministic optimization problems. The main purpose of
    the toolbox is for optimization of computationally expensive black-box objective functions with continuous and/or integer
    variables where the number of evaluations is limited. If there are several processors available it may make sense to evaluate
    the objective function using either asynchronous or synchronous parallel. pySOT uses the event-driven framework for
    asynchronous optimization strategies POAP (https://github.com/dbindel/POAP) to provide this functionality.
  doc_url: http://http://pysot.readthedocs.io/
  dev_url: https://github.com/dme65/pySOT

extra:
  recipe-maintainers:
    - tadeu
