{% set name = "pySOT" %}
{% set version = "0.2.3" %}
{% set sha256 = "025162c3eaacd073774d28662dacb689720d2e22a6911b9ae7722ac63a8bc14c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - scipy
    - pydoe2
    - poap >=0.1.25
    - py_dempster_shafer

  run:
    - python
    - scipy
    - pydoe2
    - poap >=0.1.25
    - py_dempster_shafer
    - six
    - dill
    - pytest

test:
  imports:
    - pySOT
    - pySOT.tests

  source_files:
    - pySOT/tests

  commands:
    - cd pySOT
    - cd tests
    - python test_auxiliary_problems.py
    - python test_controller.py
    - python test_experimental_designs.py
    - python test_optimization_problems.py
    - python test_strategies.py
    - python test_surrogates.py
    - python test_utils.py
    
  requires:
    - scikit-learn ==0.18.1
    
about:
  home: https://github.com/dme65/pySOT
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: 'Surrogate Optimization Toolbox'
  description: |
    pySOT is an asynchronous parallel optimization toolbox for global deterministic optimization problems. The main purpose of
    the toolbox is for optimization of computationally expensive black-box objective functions with continuous and/or integer
    variables where the number of evaluations is limited. If there are several processors available it may make sense to evaluate
    the objective function using either asynchronous or synchronous parallel. pySOT uses the event-driven framework for
    asynchronous optimization strategies POAP (https://github.com/dbindel/POAP) to provide this functionality.
  doc_url: http://http://pysot.readthedocs.io/
  dev_url: https://github.com/dme65/pySOT

extra:
  recipe-maintainers:
    - tadeu
    - jaimeambrus
