travis:
  secure:
    BINSTAR_TOKEN: Lektk0mP9+a0e0AAOqFrimxOsnx2iyscT480rS3ncVl1seJmfG1ze5EvD/ogm+ztSOCRkHx0XBqIXByZ4Ql4p5ZV3VkZ9qKQYHQZaVd33NyhhfFuenrIHpGl+AgSylLTGg/3MI+OqLzzmQ6yEyXGlKN1pwZgrFzwvWljnIhx9ZpNmMoDzYcNJn0My1EbemngMGtmXvOq9BTTH/H+exAKXgFhxIA919Jt5+McgKDoX5X65KwqSZTkRe5VfywZv9ckF3IB9XYEiy+ThQeMCYwzo3Q13VGTihRehWUQACpKlNcZzOG03E+3/2WGmZhR/3CtyMOzMfV/0esD4Q3hlbs3E9UPhcbuSxlOGqQ8vZhTWY51FF6TGRkGoORh2Dw/FP7/xtjr3CU2wglge0I2GdqTMia3U3iRQO5W79qDxZtbS+/9BZxI5bvmXZfmrD3OwWqkCXpq5YRwgHDzlvuIRCtskB/G0r/No8VG2cnzKw2163IRo7wKLVbCCTBsEDdRDvy1y1LiyCU7Xxj6MwWowm5a2egMScx208eiLMFRBiSgSahncggu2fIZSX8hDIGXWp9Wd+BlWMnql4SmYnL8m5qLCMaxODpA+tWfNIHso5UwK7II3g8fVKjJwRS7qXXZ3cLY+MotllCk/c0V4Pfaocjd4s+xjzFW8w5v97yPBEG2ibw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
